import "dotenv/config"


const ENV ={
    PORT:process.env.PORT,
    JWT_ACCESS_TOKEN_SECRET:process.env.JWT_ACCESS_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_SECRET:process.env.JWT_REFRESH_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRATION_TIME:process.env.ACCESS_TOKEN_EXPIRATION_TIME,
    REFRESH_TOKEN_EXPIRATION_TIME:process.env.REFRESH_TOKEN_EXPIRATION_TIME,
    REFRESH_TOKEN_HASH_SECRET:process.env.REFRESH_TOKEN_HASH_SECRET,
}


export default ENV;